#+TITLE: Notes from "An Introduction to Computer Architecture"
#+SUBTITLE: chapter 1 in "Designing Embedded Hardware, 2nd edition, by John Catsoulis"
#+SUBTITLE: (notes taken while working for A. Sandoz' course "Introduction aux Systèmes Informatiques")
#+AUTHOR: Daniel Kessler 

Note: the book starts with a quote R. Pirsig's Zen and the Art of Motorcycle Maintenance ;-)

* desktop computer vs embedded systems
  multi-app vs single app, but both can have their software changed
  user-decided app in volaile memory vs single app in non-volatile memory

* computer = data processor
  reminder: all data is stored as numbers (binary)
  the computer is always moving and processing numbers
  memory for programs and data, both as numbers

* Layers
  each layer usually communcates only with its immediate neighbours
  - Desktop: Hardware < Firmware < OS < Applications
  - Complex Embedded Computer: Hardware < Firmware < OS < Application(s)
  - Simple Embedded System: Hardware < Application in Firmware

** Firmware
  programs to initialize other hardware subsystems to a known state and
  configure computer for correct operation - stored permanently in computer's
  memory
  In particular, firmware contains the *bootloader* that reads the OS and places
  it in memory

** OS
  controls operation; organizes use of memory, controls devices (kbd, screen,
  drives, ...) and often provides interface to user enabling them to run
  application programs and access files on disk; also provides software tools to
  applications enabling the to access the devices the OS controls

** Application software (vs System software: everything below)
   boundary betweeen app and sys soft often blurred in embedded systems

* Processor
  "computing part of the computer", designed to manipulate data as specified by
  a sequence of instructions (**opcodes** or **machine code**)
  Each type of processor has its own **instruction set**
** microprocessor vs microcontroller vs SoC
   \mu-proc for desktop, \mu-controller for embedded system with memory on-chip,
   system-on-chip for embedded systems with separate memory
** Von Neumann machine
   instructions read from memory; data read and written from/to memory
   a.k.a. control-flow computers (almost all current computers)
   specific characteristics:
   - no real difference between data and instructions
     allows changing the instructions (treating them as data)
   - data has no inherent meaning
     no distinction between a number representing a pixel or a character, e.g.
   - data and instructions share the same memory
     instructions of a program may be treated as data by another program
     (e.g. by a compiler)
   - memory is a linear (1d) array of storage locations
  exception: Harvard architecture (data and code are in separate spaces)
* Memory addressing
  memory space = address space, partitioned by **memory map**
  often I/O devices exist in the same address space as memory devices
  (memory-mapped I/O)
* Buses
  bus = group of signal lines with a related function, with a "width" in bits
  usually, 3 buses: *address bus*, *data bus* and *control bus*
  (address from processor to memory, the other two bidirectional)
  control bus e.g. indicates from processor to memory if access is R or W,
  and from memory if valid address (or address error); also other lines usually
  for reset, interrupts and clock input
* 6 basic processor operations (or 4 if "mem=I/O")
  - write data to memory or to I/O device
  - read data from memory or from I/O device
  - read instructions from memory
  - perform internal manipulation of data within processor
* internal data storage of processor = registers
  limited number, for current data/operands
* ALU: Arithmetic Logic Unit
     Control inputs
          |||
          VVV
-operand->
--carry-->ALU--result->
-operand->
          |||
          VVV
     Status outputs

The ALU performs one operation at a time (e.g. add, sub, not, or, xor, rshift,
lshift, rotleft, rotright) on operands obtained from registers, placing result
in a register [or directly to/from memory location]
Status indicates e.g. if result was zero, negaive, overflow, carry, etc.
Sometimes separate units are used for mult, division and bit shifting
* Interrupts (= traps = exceptions)
divert processor from current program to deal with event, e.g. error from
peripheral, end of some task from I/O device (e.g. key typed, mouse moved...)
it's like a hardware-generated function call
Interrupts have priorities.
Effect: save state by pushing registers and program counter onto stack, then
load **interrupt vector** into program counter, ie address at which the ISR
(interrupt service routine) resides, the last instruction of which is a 
**return from interrupt** instruction, causing to reload saved state from stack.
NB: some processors have **shadow registers** for saving current state instead
of pushing to stack, saving memory access (and time), but only for a single (not
multiple) interrupt.
** hardware interrupts
the alternative is **busy waiting** or **polling**, ie the processor asking the
device's status register until it's ready (wasting processor's time).
Simple processors have a single interrupt input for devices, thus triggering
polling of all devices when one of them generates the interrupt - rather than
continuously polling.
More complex processors use **vectored interrupts**, where the interrupting
device provides a vector with information about the request, reducing time (can
provide just device id or more info if both device and processor permit - most
processors don't)
** fast hardware interrupts
these don't save the whole state but only the program counter, the ISR being
responsible for manually saving registers if needed; they are triggered by a
different line and are reserved for I/O devices requiring very fast response
** software interrupts
This is the lowest priority interrupt, where a program requests a service from
the system software (OS or firmware); this is not done as a regular function
call to ensure compatibility with future versions of the system (where the
required routine may be at a different memory address)
* CISC vs RISC
CISC: Complex Instruction Set Computer, e.g. intel x86, motorola 68xxx
RISC: Reduced Instruction Set Computer, e.g. IBM powerpc, MIPS, sun SPARC, ARM

CISC: single processing unit, external memory and small register set but many
instructions, up to 1000 opcodes or so. Uses less memory as each instruction
does more, and makes assembly-language programming easier *but* processors
become very complicated, and control and instruction decode units become complex
and slow. This was the trend in the 70s and 80s ("like mainframes but smaller")

RISC: once memory became cheaper, stremalining the instruction set of processors
made them simpler and faster; also, better compilers make this performant also
for complex situations: complexity "moved from the silicon to the language
compiler": keep hardware simple and fast.
Examples: xor a register with itself <=> clear, so clear not needed as an opcode;
      load a literal number in register <=> clear, then add number to register
 so (xor, store, add) can also reproduce (clear reg, clear mem, load literal)
NB: RISC processors have large register sets (sometimes over 1000!) to reduce
access to external memory, which helps compilers optimize processor performance.
Also, all instructions can be of same length, making decoding simpler.

RISC is a load/store architecture: load and store are the only instructions
refering to memory. Everything else operates on registers. This makes a 1
intruction/cycle possible and pipelining (queue next instructions) useful.

For embedded systems: prefer RISC to save power or CISC to save program storage space.
* Digital Signal Processors (DSP)
  processor optimized for numerical processing of array data
  split data and code spaces (like Harvard architecture processors) with several
  separate data banks
  specialized hardware: **hardware looping** or **zero-overhead looping**
  increase speed of arithmetics wih "multiply-and-accumulate" (MAC) units and others.
  -> common in embedded applications.
* Memory types
** typical tradeoffs:
  - persistent (when power off) but slow
  - high-capacity but requiring extra support circuity (slowing access)
  - fast but small
** organization
   by bits, nybbles (4 bits), bytes (8 bits) or words (16 or 32 bits)
   Examples, for the same amount of storage:
   -> noted 4M x 1 (4Mb of bit-organized, e.g. DRAM - dynamic RAM)
   -> noted 512K x 8 (512kB of byte-organized, e.g. SRAM - static RAM)
** RAM - random access memory... is a misnomer
   all memory is random-access, really, but RAM stuck as an acronym for "working
   memory", generally **volatile** (loses contents when power off)
   - SRAM is fastest and low consumption but low capacity and expensive; based
     on pairs of *logic gates*
   - DRAM based on arrays of *capacitors*, so need constant refreshing, ie
     constant support; impractical for small \mu-controllers
   - cache: local memory (generally) internal to processor, made of very fast
     SRAM
** ROM - read-only memory... also a misnomer
   - many modern ROMs are actually writable...
   - ROM is **non-volatile**, i.e. needs no power to keep its content
   - it is generally slower than RAM, definitely much slower than SRAM used
     mostly for **firmware** (to intialize I/O devices into a known state and
     load an OS from elsewhere)
   - \mu-controllers usually have on-chip ROM (simplifies design)
   - it is essentially made of large arrays of *diodes*, hence "burning the
     ROM", ie sending large current to "burn" some of the diodes
** EPROM vs OTP
   - "erasable programmable" vs "one-time programmable"
   - EPROM erased via UV light, making it reprogrammable, *but* must be removed
     from circuit to be erased and erasing is slow (minutes)
   - disappearing in favour of EEROM
** EE[P]ROM
   Electrically Erasable [Programmable] ROM can be erased and reprogrammed
   in-circuit, but has lower capacity than other ROM. Hence good for sys params
   and mode info but less so for firmware. Useful in embedded systems for
   storing network addresses, config settings, serial numbers, etc.
** Flash
   Newest and currently dominant type of EEROM (a.k.a. "Flash ROM" of "Flash
   RAM").
   Individual sectors can be erased/rewritten independently from each other, ie
   erasing needed as in other ROM but not of the whole device.

* Input/Output
  Reminder: address space of processor may contain devices other than memory,
  namely I/O devices, a.k.a. **peripherals**, used to communicate with the
  external world (serial controllers communicating with kbd, mouse, etc;
  parallel for external subsystem; disk-drive controllers; video/audio
  controllers; network interfaces, ...).
  
  Communication may be Programmed I/O (processor accepts/delivers data when
  convenient) or Interrupt-driven I/O (device requests suspension of current
  program to service it), or Direct Memory Access (DMA), allowing I/O to
  transfer to/from memory directly (granting higher speed, not supported by all
  processors).
* DMA - Direct Memory Access
  DMAC - DMA Controller does high-speed transfers between memory and I/O devices
  rather than byte-by-byte (or word-by-word) transfer via processor.
  DMAC needs access to address bus and data bus. Usually processor "realeases"
  buses for DMAC to "take over" for a short time.
  There are several types of DMA (see pp 38-39).
* Parallel / Distributed Computers
  increasingly common: parallel processors in one machine or distributed in
  several communicating (possibly embedded) machines
  von Neumann machine is sequential so program most be translated this way,
  inefficient for many algorithms => parallel processors help speed-up computations
  *grain*: number of processors -> coarsely grained: a few; finely grained, possibly 10'000 processors
** SIMD - Single-Instruction Multiple-Data computer
  Large arrays of simple processors; ex: CM-1 connected to Vax or Sun "host" computer 
  drawback: too specialized (need problems that can be broken down in tiny
  similar calcs)
** MIMD - Multiple-Instruction Multiple-Data computer
   coarsely grained collection of semi-autonomous processors
   - shared-memory: each processor has a cache + access to shared main memory
     including table of processes, from where to fetch a process from a queue
   - message-passing: each processor has its own main memory with its own
     programs to execute; the processors communicate throug a bus (e.g. via
     ethernet)
     => distributed machine = lossely coupled MIMD, common for embedded machines
* Embedded Computer Architecture
** what determines its functionality: (p.46 -> quote it in project)
   - what a computer is used for
   - what tasks it must perform
   - how humans and other systems interact with it
** microcontrollers used as processor
   incorporate most of the functionality on a single chip
   block diagrams: see p47 and p48
   -> microcontroller has CPU, ROM and/or RAM, some type of I/O, all "subsystem blocks"
** GPIO = General-Purpose I/O = digital I/O   
   same pins can be used as input or output (configured by software)
   -> I: read state of switches or push buttons; read digital status of other device
   -> O: turn external device on/off; convey status to external device
** analog inputs
   microcontrollers may have them to allow sampling of sensors (for monitoring
   or recording), e.g. to measure light levels, temperature, vibration,
   accelaration, air or water pressure, humidity, magnetic field, etc...
   or just a simple voltage
** I/O subsystems (very variable)
   - serial ports enable mcirocontroller to interface to host computer, modem or
     other embedded system (e.g. to expand functionality) e.g. off-the-chip
     memories, clock/calendar chips, sensors with digital interfaces, external
     analog I/O, audio chips, etc...
   - most microcontrollers already timers and counters used to generate regular
     interrupts for multitasking, triggers for off-chip systems or count
     external triggers (pulses)
   - some microcontrollers also have USB, ethernet or such network interfaces
   - some larger \mu-controllers also have a bus interface allowing
     interfacing with peripherals like a regular processor
